/**
 * Seed data for transition levers
 */

export const TRANSITION_LEVERS_SEED = [
  {
    leverId: 'L001',
    leverName: 'Renewable electricity (on-site)',
    category: 'energy',
    description: 'Install on-site solar/wind generation to displace grid electricity',
    applicableIndustries: ['chemicals', 'petrochemicals', 'manufacturing'],
    trl: 9,
    maturity: 'mature',
    emissionReductionRange: { min: -2, max: -8, unit: '%_emissions_per_year' },
    capexRange: { min: 5, max: 50, perUnit: 'per_facility' },
    opexRange: { min: 0.5, max: 2, recurring: true },
    paybackRange: { min: 8, max: 12 },
    implementationDuration: { min: 1, max: 2 },
    technicalRisk: 'low',
    marketRisk: 'low',
    regulatoryRisk: 'low',
    sbtEligible: true,
  },
  {
    leverId: 'L002',
    leverName: 'Renewable electricity (PPAs)',
    category: 'energy',
    description: 'Power Purchase Agreements for wind/solar from third-party generators',
    applicableIndustries: ['chemicals', 'petrochemicals', 'manufacturing'],
    trl: 9,
    maturity: 'mature',
    emissionReductionRange: { min: -1, max: -5, unit: '%_emissions_per_year' },
    capexRange: { min: 0, max: 5, perUnit: 'per_facility' },
    opexRange: { min: 2, max: 5, recurring: true },
    paybackRange: { min: 5, max: 8 },
    implementationDuration: { min: 1, max: 2 },
    technicalRisk: 'low',
    marketRisk: 'medium',
    regulatoryRisk: 'low',
    sbtEligible: true,
  },
  {
    leverId: 'L003',
    leverName: 'Energy efficiency (buildings)',
    category: 'energy',
    description: 'Building envelope improvements, HVAC optimization, controls',
    applicableIndustries: ['chemicals', 'petrochemicals', 'manufacturing'],
    trl: 9,
    maturity: 'mature',
    emissionReductionRange: { min: -1, max: -3, unit: '%_emissions_per_year' },
    capexRange: { min: 2, max: 10, perUnit: 'per_facility' },
    opexRange: { min: 0.2, max: 0.8, recurring: true },
    paybackRange: { min: 3, max: 5 },
    implementationDuration: { min: 1, max: 2 },
    technicalRisk: 'low',
    marketRisk: 'low',
    regulatoryRisk: 'low',
    sbtEligible: true,
  },
  {
    leverId: 'L004',
    leverName: 'Energy efficiency (process)',
    category: 'energy',
    description: 'Process optimization, equipment upgrades, monitoring/controls',
    applicableIndustries: ['chemicals', 'petrochemicals', 'manufacturing'],
    trl: 8,
    maturity: 'mature',
    emissionReductionRange: { min: -2, max: -6, unit: '%_emissions_per_year' },
    capexRange: { min: 5, max: 30, perUnit: 'per_facility' },
    opexRange: { min: 1, max: 3, recurring: true },
    paybackRange: { min: 4, max: 7 },
    implementationDuration: { min: 1, max: 3 },
    technicalRisk: 'low',
    marketRisk: 'low',
    regulatoryRisk: 'low',
    sbtEligible: true,
  },
  {
    leverId: 'L007',
    leverName: 'Waste heat recovery',
    category: 'energy',
    description: 'Capture and reuse waste heat from processes',
    applicableIndustries: ['chemicals', 'petrochemicals', 'manufacturing'],
    trl: 8,
    maturity: 'mature',
    emissionReductionRange: { min: -1, max: -3, unit: '%_emissions_per_year' },
    capexRange: { min: 3, max: 15, perUnit: 'per_facility' },
    opexRange: { min: 0.3, max: 1, recurring: true },
    paybackRange: { min: 5, max: 8 },
    implementationDuration: { min: 1, max: 2 },
    technicalRisk: 'medium',
    marketRisk: 'low',
    regulatoryRisk: 'low',
    sbtEligible: false,
  },
  {
    leverId: 'L011',
    leverName: 'Electrification (furnaces/drying)',
    category: 'process',
    description: 'Replace fossil fuel heating with electric heating powered by renewables',
    applicableIndustries: ['chemicals', 'petrochemicals'],
    trl: 6,
    maturity: 'growth',
    emissionReductionRange: { min: -3, max: -8, unit: '%_emissions_per_year' },
    capexRange: { min: 20, max: 100, perUnit: 'per_facility' },
    opexRange: { min: 2, max: 6, recurring: true },
    paybackRange: { min: 12, max: 20 },
    implementationDuration: { min: 2, max: 4 },
    technicalRisk: 'medium',
    marketRisk: 'medium',
    regulatoryRisk: 'low',
    sbtEligible: true,
  },
  {
    leverId: 'L013',
    leverName: 'Hydrogen (green H₂ from renewables)',
    category: 'process',
    description: 'Replace gray hydrogen with green hydrogen from renewable electricity',
    applicableIndustries: ['chemicals', 'petrochemicals'],
    trl: 5,
    maturity: 'emerging',
    emissionReductionRange: { min: -2, max: -10, unit: '%_emissions_per_year' },
    capexRange: { min: 50, max: 150, perUnit: 'per_facility' },
    opexRange: { min: 5, max: 15, recurring: true },
    paybackRange: { min: 15, max: 25 },
    implementationDuration: { min: 3, max: 5 },
    technicalRisk: 'high',
    marketRisk: 'high',
    regulatoryRisk: 'medium',
    sbtEligible: true,
  },
  {
    leverId: 'L015',
    leverName: 'Circularity (recycled feedstock)',
    category: 'process',
    description: 'Use recycled materials as feedstock instead of virgin materials',
    applicableIndustries: ['chemicals', 'petrochemicals', 'manufacturing'],
    trl: 7,
    maturity: 'growth',
    emissionReductionRange: { min: -1, max: -5, unit: '%_emissions_per_year' },
    capexRange: { min: 5, max: 25, perUnit: 'per_facility' },
    opexRange: { min: 0.5, max: 2, recurring: true },
    paybackRange: { min: 6, max: 10 },
    implementationDuration: { min: 2, max: 3 },
    technicalRisk: 'medium',
    marketRisk: 'medium',
    regulatoryRisk: 'low',
    sbtEligible: true,
  },
  {
    leverId: 'L016',
    leverName: 'Supplier engagement (low-carbon purchasing)',
    category: 'supply_chain',
    description: 'Engage suppliers to reduce emissions in supply chain',
    applicableIndustries: ['chemicals', 'petrochemicals', 'manufacturing'],
    trl: 8,
    maturity: 'mature',
    emissionReductionRange: { min: -2, max: -8, unit: '%_emissions_per_year' },
    capexRange: { min: 0, max: 2, perUnit: 'lump_sum' },
    opexRange: { min: 0.1, max: 0.5, recurring: true },
    paybackRange: { min: 2, max: 4 },
    implementationDuration: { min: 1, max: 1 },
    technicalRisk: 'low',
    marketRisk: 'medium',
    regulatoryRisk: 'low',
    sbtEligible: true,
  },
  {
    leverId: 'L021',
    leverName: 'Carbon offsets (reforestation, soil)',
    category: 'removal',
    description: 'Purchase carbon offset credits from verified projects',
    applicableIndustries: ['chemicals', 'petrochemicals', 'manufacturing'],
    trl: 8,
    maturity: 'mature',
    emissionReductionRange: { min: -1, max: -5, unit: '%_emissions_per_year' },
    capexRange: { min: 1, max: 10, perUnit: 'lump_sum' },
    opexRange: { min: 0.5, max: 3, recurring: true },
    paybackRange: { min: 2, max: 4 },
    implementationDuration: { min: 1, max: 1 },
    technicalRisk: 'low',
    marketRisk: 'high',
    regulatoryRisk: 'medium',
    sbtEligible: false,
  },
];

export async function seedTransitionLevers(): Promise<void> {
  try {
    const { countTransitionLeverTemplates, upsertTransitionLeverById } = await import('../data/seedDataAccess.ts');
    const count = await countTransitionLeverTemplates();
    if (count > 0) {
      console.log(`✓ Transition levers already seeded (${count} records). Skipping seed.`);
      return;
    }

    console.log('Seeding transition levers...');
    for (const lever of TRANSITION_LEVERS_SEED) {
      await upsertTransitionLeverById(lever.leverId, lever as Record<string, unknown>);
    }
    console.log(`✓ Seeded ${TRANSITION_LEVERS_SEED.length} transition levers`);
  } catch (error) {
    console.error('Failed to seed transition levers:', error);
    throw error;
  }
}
